version: '3'

services: 
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
  mysql:
    image: mysql:5.7
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: projekt
      MYSQL_USER: projekt
      MYSQL_PASSWORD: projekt
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql
    container_name: db
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    container_name: phpmyadmin
    restart: always
    ports:
      -   "8081:80"
volumes:
  db-vol: